map_type: costmap

obstacle_range: 1.5
raytrace_range: 2.0

transform_tolerance: 0.5

inflation_radius: 1.75
cost_scaling_factor: 2.25

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /udacity_bot/laser/scan, marking: true, clearing: true}
